"""
Swap Pair A flankers → Pair B flankers across every file in
app/public/brand/pacific-kings/, adjusting the LEFT flanker's x-translate
so its ink right-edge stays in the same place (keeps the gap to P intact).

Scope:
  - pacific-kings-lockup{,-ink,-cream,-vermillion}.svg
  - social-*.svg                                       (17 files)
  - pacific-kings-lockup-stacked*.svg are REGENERATED by a separate
    script after this runs, since the stacked variant uses a different
    flanker scale (2.45 vs 1.1968).

NOT touched:
  - pacific-kings-lockup-alt-teardrop.svg  (intentional alternate)
  - pacific-kings-wordmark.svg             (no flankers)
  - favicon*.svg
"""
from __future__ import annotations

import re
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

REPO = Path.home() / "Documents/projects/future/future-repo"
BRAND = REPO / "app/public/brand/pacific-kings"
FONT = REPO / "app/public/fonts/OhnoBlazeface-72Point.otf"

FLANKER_SCALE = 1.1968
FLANKER_BASELINE_Y = 907.4


def extract_glyph(font: TTFont, cp: int):
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    glyph = gs[cmap[cp]]
    pen = SVGPathPen(gs)
    glyph.draw(pen)
    bounds = BoundsPen(gs)
    glyph.draw(bounds)
    return pen.getCommands(), glyph.width, bounds.bounds  # (xmin, ymin, xmax, ymax)


def build_flanker_group(path_d: str, translate_x: float) -> str:
    """Same transform shape as the existing lockup flanker `<g>`."""
    return (
        f'<g transform="translate({translate_x},{FLANKER_BASELINE_Y}) '
        f'scale({FLANKER_SCALE},-{FLANKER_SCALE})"><path d="{path_d}"/></g>'
    )


def main():
    font = TTFont(str(FONT))

    # Pair A (to be replaced)
    a_left_d,  a_left_w,  a_left_bb  = extract_glyph(font, 0xE000)
    a_right_d, a_right_w, a_right_bb = extract_glyph(font, 0xE001)

    # Pair B (new canonical)
    b_left_d,  b_left_w,  b_left_bb  = extract_glyph(font, 0xE002)
    b_right_d, b_right_w, b_right_bb = extract_glyph(font, 0xE003)

    print("Pair A left  advance:", a_left_w,  "bounds:", a_left_bb)
    print("Pair A right advance:", a_right_w, "bounds:", a_right_bb)
    print("Pair B left  advance:", b_left_w,  "bounds:", b_left_bb)
    print("Pair B right advance:", b_right_w, "bounds:", b_right_bb)

    # Existing lockup has:
    #   LEFT flanker at translate(-35.9, 907.4)
    #   RIGHT flanker at translate(9547.7, 907.4)
    # Pair A bounds give us the visual right-edge of the left flanker
    # and the visual left-edge of the right flanker. We want Pair B
    # to occupy the same visual positions so the gap to the letters
    # is preserved.

    A_LEFT_X = -35.9
    A_RIGHT_X = 9547.7

    # Right ink edge of Pair A left flanker in SVG coords:
    a_left_ink_right = A_LEFT_X + a_left_bb[2] * FLANKER_SCALE
    # Left ink edge of Pair A right flanker in SVG coords:
    a_right_ink_left = A_RIGHT_X + a_right_bb[0] * FLANKER_SCALE
    print(f"Pair A left ink right-edge: {a_left_ink_right:.2f}")
    print(f"Pair A right ink left-edge: {a_right_ink_left:.2f}")

    # Solve for Pair B x that puts ink in the same place:
    #   new_x + b_left_bb[2] * scale = a_left_ink_right
    B_LEFT_X  = a_left_ink_right - b_left_bb[2] * FLANKER_SCALE
    #   new_x + b_right_bb[0] * scale = a_right_ink_left
    B_RIGHT_X = a_right_ink_left - b_right_bb[0] * FLANKER_SCALE
    print(f"Pair B left new translate x:  {B_LEFT_X:.2f}")
    print(f"Pair B right new translate x: {B_RIGHT_X:.2f}")

    # Build the exact strings we'll grep/replace.
    # Match the exact format used in the existing files:
    #   <g transform="translate(-35.9,907.4) scale(1.1968,-1.1968)"><path d="M103..."/></g>
    old_left  = f'<g transform="translate(-35.9,907.4) scale(1.1968,-1.1968)"><path d="{a_left_d}"/></g>'
    old_right = f'<g transform="translate(9547.7,907.4) scale(1.1968,-1.1968)"><path d="{a_right_d}"/></g>'

    # New strings with Pair B paths and adjusted x.
    new_left = (
        f'<g transform="translate({B_LEFT_X:.1f},907.4) scale(1.1968,-1.1968)">'
        f'<path d="{b_left_d}"/></g>'
    )
    new_right = (
        f'<g transform="translate({B_RIGHT_X:.1f},907.4) scale(1.1968,-1.1968)">'
        f'<path d="{b_right_d}"/></g>'
    )

    # Files to touch
    SKIP = {
        "pacific-kings-lockup-alt-teardrop.svg",
        "pacific-kings-wordmark.svg",
        # Stacked lockups will be regenerated from scratch:
        "pacific-kings-lockup-stacked.svg",
        "pacific-kings-lockup-stacked-ink.svg",
        "pacific-kings-lockup-stacked-cream.svg",
        "pacific-kings-lockup-stacked-vermillion.svg",
    }

    svgs = sorted(p for p in BRAND.glob("*.svg")
                  if not p.name.startswith("favicon")
                  and p.name not in SKIP)

    print(f"\nProcessing {len(svgs)} SVGs...")
    left_hits_total = right_hits_total = 0
    for svg_path in svgs:
        text = svg_path.read_text()
        new_text = text
        left_hits  = new_text.count(old_left)
        right_hits = new_text.count(old_right)
        if left_hits == 0 and right_hits == 0:
            print(f"  SKIP  {svg_path.name:<50} (no Pair A flankers found)")
            continue
        new_text = new_text.replace(old_left,  new_left)
        new_text = new_text.replace(old_right, new_right)
        svg_path.write_text(new_text)
        left_hits_total  += left_hits
        right_hits_total += right_hits
        print(f"  OK    {svg_path.name:<50} (left:{left_hits} right:{right_hits})")

    print(f"\nTotal replacements: {left_hits_total} left, {right_hits_total} right")
    print("Horizontal swap complete. Now re-run the stacked builder for pair B.")


if __name__ == "__main__":
    main()
